import { defineConfig } from 'vite-plus';

export default defineConfig({
  staged: {
    '*': 'vp check --fix',
  },
  // ── No JS packaging at the root ──
  // Every browser bundle now lives in @getvitops/core (packages/core/vite.config.ts),
  // including the live theme editor — `editor.js` used to be a root-only docs script
  // and is now `@getvitops/core/editor`. It reaches dist/ through the generator's
  // asset copy like the other bundles, so there's no root `pack` (and no need for
  // the `clean: false` that kept it from wiping build:theme's output).

  // ── Lint / format (Oxlint / Oxfmt, via `vp check` / `vp fmt`) ──
  lint: {
    // apps/** is a self-contained playground with its own Astro toolchain — not
    // linted by the root oxlint (Astro/JSX/framework imports aren't in scope here).
    ignorePatterns: [
      'dist/**',
      'node_modules/**',
      'packages/*/dist/**',
      'packages/generator/assets/**',
      // Scaffold sources for `vp create @getvitops:*` — they import deps that
      // only exist in a scaffolded project, so type-aware lint can't see them.
      'packages/create/templates/**',
      'apps/**',
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
  fmt: {
    semi: true,
    singleQuote: true,
    // Don't format generated/build output: the codegen emits its own style, so
    // formatting it just creates churn against the next `vp run build`.
    // docs/** is generated by @getvitops/generator's docs.ts (via build:theme).
    ignorePatterns: [
      'dist/**',
      'src/css/generated/**',
      'docs/**',
      // Generated by the `design` format (build:design) — reformatting it would
      // churn the diff on every build without changing what the file says.
      'DESIGN.md',
      'node_modules/**',
      'packages/*/dist/**',
      'packages/generator/assets/**',
      'packages/generator/schema.json',
      'apps/**',
    ],
  },

  // ── Tasks (Vite Task, via `vp run <name>`) ──
  run: {
    tasks: {
      dev: { command: 'vp dev', dependsOn: ['build', 'build:docs', 'build:design'] },

      // Default full build → the Bricks target. Format-specific full builds are
      // separate `build:<type>` tasks (not a `--format` flag: vp appends
      // forwarded args to the command tail, which would corrupt the last
      // sub-task, and vp only resolves `vp run <task>` in-process when it appears
      // literally in the command — a wrapper that could parse the flag breaks it).
      build: { command: 'vp run build:bricks' },

      // Bricks full build: dogfood @getvitops/generator to emit the whole theme dist.
      'build:bricks': {
        command: 'vp run build:theme',
      },

      // Framework runtime bundles (polyfills/deferred/elements) — built by @getvitops/core.
      // build:generator snapshots these into its package assets; build:theme copies them
      // into dist/. Runs first (build:generator dependsOn it).
      'build:core': {
        command: 'cd packages/core && vp pack',
        dependsOn: ['build:utils'],
        input: ['packages/core/src/**/*.ts', 'packages/core/vite.config.ts'],
        output: ['packages/core/dist/**'],
      },

      // Theme dist via @getvitops/generator (dogfood). Emits styles.min.css (bundled by
      // core's lightningcss *library* — no CLI), the Bricks import JSON, tokens.json,
      // the JS bundles + bricks/ PHP + docs/ (copied from the package assets). Replaces
      // the old generate:theme + build:css + build:elements. dependsOn build:generator so the
      // library is built and its assets are synced from the fresh JS bundles first.
      'build:theme': {
        command: 'node lib/build-theme.ts',
        dependsOn: ['build:generator'],
        input: [
          'lib/build-theme.ts',
          'src/design-system.json',
          'packages/generator/dist/index.mjs',
          'packages/generator/assets/**',
        ],
        output: [
          'dist/styles.min.css*',
          'dist/bricks*.json',
          'dist/tokens.json',
          'dist/bricks/**',
          'dist/docs/**',
          // The tracked mirror of the docs bundle (dist/ is gitignored).
          'docs/**',
        ],
      },

      // Standalone CSS bundle for the docsite (index.html) via core's css format:
      // dist/styles.css + design-manifest.json (self-contained — tokens/fonts/scales).
      'build:docs': {
        command: 'node lib/build-theme.ts --format css',
        dependsOn: ['build:generator'],
        input: [
          'lib/build-theme.ts',
          'src/design-system.json',
          'packages/generator/dist/index.mjs',
          'packages/generator/assets/**',
        ],
        output: ['dist/styles.css', 'dist/design-manifest.json', 'dist/tokens.json'],
      },

      // Tailwind v4 bundle for Astro/EmDash consumers via core's tailwind format:
      // one self-contained dist/tailwind.css + tokens.json.
      'build:tailwind': {
        command: 'node lib/build-theme.ts --format tailwind',
        dependsOn: ['build:generator'],
        input: [
          'lib/build-theme.ts',
          'src/design-system.json',
          'packages/generator/dist/index.mjs',
          'packages/generator/assets/**',
        ],
        output: ['dist/tailwind.css', 'dist/tokens.json'],
      },

      // The agent-facing brief (google-labs-code/design.md format) via core's
      // design format. Unlike every other build:* target this writes to the repo
      // ROOT and the file is tracked — DESIGN.md belongs beside AGENTS.md, and
      // an agent reading the repo should find it without a build having run.
      'build:design': {
        command: 'node lib/build-theme.ts --format design',
        dependsOn: ['build:generator'],
        input: [
          'lib/build-theme.ts',
          'src/design-system.json',
          'packages/generator/dist/index.mjs',
          'packages/generator/assets/**',
        ],
        output: ['DESIGN.md'],
      },

      // ── Publishable packages (@getvitops/{core,generator,utils,cli,vite}) ──
      // `build:generator` snapshots the framework-static assets (CSS + JS bundles
      // from @getvitops/core) + emits the JSON Schema (prepare.mjs), then bundles
      // the library; it dependsOn build:core so core's JS bundles exist first.
      // cli/vite build after generator + utils (they import them).
      // Each package's `vp pack` reads its own packages/*/vite.config.ts.
      'build:generator': {
        command: 'node packages/generator/scripts/prepare.mjs && cd packages/generator && vp pack',
        dependsOn: ['build:core'],
        input: [
          'packages/generator/src/**/*.ts',
          'packages/generator/scripts/prepare.mjs',
          'packages/generator/vite.config.ts',
          'packages/core/css/**',
          'packages/core/dist/**',
          'bricks/**/*.php',
          'src/design-system.json',
        ],
        output: [
          'packages/generator/dist/**',
          'packages/generator/assets/**',
          'packages/generator/schema.json',
        ],
      },
      // Shared build-time utilities (favicon generation, …). No workspace deps.
      'build:utils': {
        command: 'cd packages/utils && vp pack',
        input: ['packages/utils/src/**/*.ts', 'packages/utils/vite.config.ts'],
        output: ['packages/utils/dist/**'],
      },
      'build:cli': {
        command: 'cd packages/cli && vp pack',
        dependsOn: ['build:generator', 'build:utils'],
        input: ['packages/cli/src/**/*.ts', 'packages/cli/vite.config.ts'],
        output: ['packages/cli/dist/**'],
      },
      'build:vite-plugin': {
        command: 'cd packages/vite && vp pack',
        dependsOn: ['build:generator', 'build:utils'],
        input: ['packages/vite/src/**/*.ts', 'packages/vite/vite.config.ts'],
        output: ['packages/vite/dist/**'],
      },
      // Astro integration: composes vite-plugin + utils (favicons) + core (the JS
      // bundles it copies into a consumer's public/). build:core provides those.
      'build:astro': {
        command: 'cd packages/astro && vp pack',
        dependsOn: ['build:core', 'build:generator', 'build:utils', 'build:vite-plugin'],
        input: ['packages/astro/src/**/*.ts', 'packages/astro/vite.config.ts'],
        output: ['packages/astro/dist/**'],
      },
      // EmDash CMS plugin: descriptor/runtime only (the ./astro entry ships as source).
      'build:emdash': {
        command: 'cd packages/emdash && vp pack',
        // The Block Kit icon options are derived from @getvitops/utils' iconMap
        // rather than copied, so the dts pass needs utils' types built. The
        // module itself stays external (it is a real `dependencies` entry).
        dependsOn: ['build:utils'],
        input: [
          'packages/emdash/src/**/*.ts',
          'packages/emdash/vite.config.ts',
          // The descriptor's `version` is imported from package.json and inlined
          // at build time, so a version-only bump MUST invalidate this task —
          // otherwise `changeset version` bumps the manifest, the cached dist
          // keeps the old number, and the descriptor ships stale. That is exactly
          // how 0.2.1 published a descriptor reading 0.2.0.
          'packages/emdash/package.json',
        ],
        output: ['packages/emdash/dist/**'],
      },
      // Build all publishable packages (cli/vite need core + utils; astro needs all).
      'build:packages': {
        command:
          'vp run build:generator && vp run build:utils && vp run build:cli && vp run build:vite-plugin && vp run build:astro && vp run build:emdash',
      },
      // Apply pending changesets: bump every package + write the per-package
      // CHANGELOG.md files. Run BEFORE `release`, then hand-write the matching
      // entry in the root CHANGELOG.md (the curated, toolchain-level notes).
      // See the release runbook in AGENTS.md.
      'release:version': {
        command: 'changeset version',
      },
      // Publish the scoped packages via Changesets. Root stays private.
      // Assumes `release:version` already ran and the root CHANGELOG.md is current.
      release: {
        // Tests gate the publish. Without this, `@getvitops/emdash@0.2.1` shipped
        // a descriptor hardcoded to 0.2.0: `changeset version` bumps package.json
        // but not the literal, and the test that asserts they match never ran.
        command: 'vp test run && vp run build:packages && changeset publish',
      },

      // Deploy: rsync dist/ to the remote theme over SSH. Depends on build so
      // it always ships a fresh, complete dist/.
      deploy: {
        command: 'node --env-file=.env lib/deploy.ts',
        dependsOn: ['build'],
      },

      // ── apps/docs (plain Astro documentation site) ─────────────────────────
      // Private, and isolated from the release DAG like apps/portal: NOT wired
      // into `build`, `build:packages`, or `deploy`. Its Reference section is
      // synced from @getvitops/generator's generateDocs() — the same bundle
      // `vitops docs` prints — so it can't drift from what the toolchain emits.
      // `docs:sync` therefore dependsOn build:generator.
      'docs:sync': {
        command: 'node apps/docs/scripts/sync-reference.mjs',
        dependsOn: ['build:generator'],
        input: [
          'apps/docs/scripts/sync-reference.mjs',
          'src/design-system.json',
          'CHANGELOG.md',
          'packages/generator/dist/index.mjs',
          'packages/generator/assets/**',
        ],
        output: [
          'apps/docs/src/content/docs/reference/**',
          'apps/docs/src/content/docs/changelog.md',
        ],
      },
      'docs:dev': {
        command: 'pnpm --filter docs exec astro dev',
        dependsOn: ['docs:sync'],
      },
      'docs:build': {
        command: 'pnpm --filter docs exec astro build',
        dependsOn: ['docs:sync'],
        output: ['apps/docs/dist/**'],
      },
      'docs:preview': {
        command: 'pnpm --filter docs exec astro preview',
      },

      // ── apps/portal (extraction-bound playground) ──────────────────────────
      // Fully isolated from the Bricks/design-system release DAG: NOT wired into
      // `build`, `build:packages`, or `deploy`, and NOT dependent on any
      // @getvitops package (the design-system CSS dogfooding is deferred while
      // that framework is in flux — the app uses its own wireframe stylesheet).
      // Migrations are plain SQL run by drizzle-orm's migrator; tests run under
      // the root vitest (vite-plus).
      'portal:dev': {
        command: 'cd apps/portal && astro dev',
      },
      'portal:build': {
        command: 'cd apps/portal && astro build',
      },
      'portal:migrate': {
        command: 'cd apps/portal && node --env-file-if-exists=.env ./scripts/migrate.ts',
      },
      'portal:seed': {
        command: 'cd apps/portal && node --env-file-if-exists=.env ./scripts/seed.ts',
      },
      // Long-lived background worker: node-cron sync + outbox dispatch.
      'portal:worker': {
        command: 'cd apps/portal && node --env-file-if-exists=.env ./src/workers/cron.ts',
      },
      'portal:test': {
        command: 'vp test run apps/portal',
      },
    },
  },
});
