/**
 * Side-effect-free helpers for the `vitops agents` / `vitops docs` commands.
 * Kept out of cli.ts (which runs main() on import) so they are unit-testable.
 */
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readlinkSync,
  rmSync,
  symlinkSync,
} from 'node:fs';
import { dirname, join, parse, relative, resolve } from 'node:path';

export const SKILL_NAME = 'vitops-design-system';

/** Marker the 0.5.0-era generated skill carried; lets us migrate that layout. */
export const GENERATED_MARKER = '<!-- GENERATED by @getvitops/cli';

/**
 * `vitops docs` topics → docs-bundle paths (as returned by `generateDocs`).
 * Order is the `--all` concatenation order.
 */
export const TOPICS: Record<string, { path: string; summary: string }> = {
  classes: {
    path: 'css/classes.md',
    summary: 'CSS framework class vocabulary (colour, type, space, layout, animation, patterns)',
  },
  authoring: {
    path: 'authoring.md',
    summary: 'every design-system.json field, rendered from the JSON Schema',
  },
  config: {
    path: 'config.md',
    summary:
      'every field of the three-section config (designSystem / organization / site), rendered from the JSON Schema',
  },
  formats: {
    path: 'formats.md',
    summary: "tailwind vs css vs bricks: what's emitted vs what the platform provides",
  },
  color: {
    path: 'concepts/color.md',
    summary: 'seeded OKLCH scales, functional tokens, automatic dark mode',
  },
  scales: {
    path: 'concepts/scales.md',
    summary: 'fluid modular type & space scales',
  },
  icons: {
    path: 'concepts/icons.md',
    summary: 'semantic icon names across sets, bundle derivation, sprite delivery',
  },
  patterns: {
    path: 'concepts/patterns.md',
    summary: 'pattern CSS: token cascade, override hooks, states, role variants',
  },
  elements: {
    path: 'bricks/elements.md',
    summary: 'Bricks Builder custom elements, controls, defaults',
  },
};

/**
 * Find the installed package's skill directory by walking up from `cwd` looking
 * for `node_modules/@getvitops/cli/skill/SKILL.md`. Returns the LOGICAL path
 * (through the `node_modules/@getvitops/cli` link, unresolved) or null.
 *
 * Deliberately not derived from import.meta.url: under pnpm the running module's
 * URL is the realpath in `node_modules/.pnpm/@getvitops+cli@<version>/…`, which
 * changes on every version bump — a symlink to it would dangle after upgrades.
 * The logical path is recreated by the package manager on every install, so a
 * link through it always resolves to the currently installed version.
 */
export function findSkillTarget(cwd: string): string | null {
  let dir = resolve(cwd);
  const { root } = parse(dir);
  for (;;) {
    const skillDir = join(dir, 'node_modules', '@getvitops', 'cli', 'skill');
    if (existsSync(join(skillDir, 'SKILL.md'))) return skillDir;
    if (dir === root) return null;
    dir = dirname(dir);
  }
}

/**
 * Idempotently symlink `linkPath` → `targetDir` (relative target). Replaces a
 * stale symlink; migrates a real directory left by the old emitting `vitops
 * agents` (identified by GENERATED_MARKER in its SKILL.md); refuses to clobber
 * anything else. Returns a warning string, or null on success / no-op.
 */
export function linkSkill(linkPath: string, targetDir: string): string | null {
  const target = relative(dirname(linkPath), resolve(targetDir));
  try {
    const st = lstatSync(linkPath, { throwIfNoEntry: false });
    if (st && !st.isSymbolicLink()) {
      const oldSkill = join(linkPath, 'SKILL.md');
      const isGenerated =
        st.isDirectory() &&
        existsSync(oldSkill) &&
        readFileSync(oldSkill, 'utf8').includes(GENERATED_MARKER);
      if (!isGenerated)
        return `left ${linkPath} alone (exists and is not a symlink) — link it to ${targetDir} yourself if wanted`;
      rmSync(linkPath, { recursive: true }); // old generated skill layout → replace
    } else if (st) {
      if (readlinkSync(linkPath) === target) return null;
      rmSync(linkPath);
    } else {
      mkdirSync(dirname(linkPath), { recursive: true });
    }
    symlinkSync(target, linkPath);
    return null;
  } catch (err) {
    return `could not symlink ${linkPath}: ${(err as Error).message}`;
  }
}
